### ISSUE TITLE
"object_detection.protos.AnchorGenerator" has no field named "yolo_anchor_generator".

### ISSUE THREAD

**Issue by mwindowshz** [GustavZ/yolo_for_tf_od_api#4]
Hi
Trying to train darknet

using orignal repo of Tensorflow object detection api
added all the files as you described in your readme.
when I try to train using darknet I receive an error:
**"object_detection.protos.AnchorGenerator" has no field named "yolo_anchor_generator".**

 Can you please help me
Thanks in advance.

> D:\tf-od-api\yolo_v2-master\research\object_detection>python train.py --logtostderr --train_dir=D:\tf-od-api\3classes\Train_Eval_Base_Dir/Darknet19_ImageNet_ckpt/train --pipeline_config_path=D:\tf-od-api\3classes\Base_Modeles_Dir\Darknet19_ImageNet_ckpt/pipeline.config
> Traceback (most recent call last):
>   File "train.py", line 164, in <module>
>     tf.app.run()
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "train.py", line 92, in main
>     FLAGS.pipeline_config_path)
>   File "C:\Yolo\DataSets\Data_For_TF_Obecect_detection_API\models-master\research\object_detection\utils\config_util.py", line 94, in get_configs_from_pipeline_file
>     text_format.Merge(proto_str, pipeline_config)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 536, in Merge
>     descriptor_pool=descriptor_pool)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 590, in MergeLines
>     return parser.MergeLines(lines, message)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 623, in MergeLines
>     self._ParseOrMerge(lines, message)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 638, in _ParseOrMerge
>     self._MergeField(tokenizer, message)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 763, in _MergeField
>     merger(tokenizer, message, field)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 837, in _MergeMessageField
>     self._MergeField(tokenizer, sub_message)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 763, in _MergeField
>     merger(tokenizer, message, field)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 837, in _MergeMessageField
>     self._MergeField(tokenizer, sub_message)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 763, in _MergeField
>     merger(tokenizer, message, field)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 837, in _MergeMessageField
>     self._MergeField(tokenizer, sub_message)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 730, in _MergeField
>     (message_descriptor.full_name, name))
> google.protobuf.text_format.ParseError: 32:7 : Message type **"object_detection.protos.AnchorGenerator" has no field named "yolo_anchor_generator".**

**Comment by rky0930** [comment]
Hi @mwindowshz 
You wrote duplicate issue both repos
I reply to rky0930/yolo_v2#5
Please check and feel free to ask more question. 
Thanks.
